//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESDAData
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string House { get; set; }
        public string PicturePath { get; set; }
        public string MedicalPath { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public string Status { get; set; }
        public System.DateTime DateOfLeave { get; set; }
    }
}
